theme: jekyll-theme-slate
title: [Deep Learning and Remote Sensing for Coastal Monitoring]
description: [Duke University Bass Connections project for monitoring land cover dynamics in the coastal Southeast US]
